version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: weekly
      timezone: America/Los_Angeles
      day: tuesday
    target-branch: "develop"
    open-pull-requests-limit: 99
